services:
  data-init:
    build: ./data-init
    volumes: 
      - data_volume:/data
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    entrypoint: ["/entrypoint.sh"]

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      data-init:
        condition: service_completed_successfully
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    entrypoint: >
      sh -c "sleep 5 && certbot certonly --webroot --webroot-path=/var/www/certbot 
      --email wankhedesamirforwork@gmail.com --agree-tos --no-eff-email 
      -d nthhost.credenz.co.in && echo '✅ Certbot finished successfully!'"
    depends_on:
      nginx:
        condition: service_healthy

  certbot-renew:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    entrypoint: >
      sh -c "certbot renew --webroot --webroot-path=/var/www/certbot && nginx -s reload"
    depends_on:
      certbot:
        condition: service_completed_successfully
    restart: unless-stopped

  backend:
    build: ./backend
    ports: 
      - "5789:3000"
    volumes:
      - data_volume:/data
    env_file:
      - .env
    depends_on:
      certbot-renew:
        condition: service_completed_successfully
    restart: unless-stopped

  admin:
    build: ./admin
    ports: 
      - "4788:4000"
    volumes:
      - data_volume:/data
    env_file:
      - .env
    depends_on:
      certbot-renew:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  data_volume:
  letsencrypt:
  certbot_challenges:
