services:
  data-init:
    build: ./data-init
    volumes: 
      - data_volume:/data
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot

  nginx-certbot:
    image: nginx:alpine
    volumes:
      - certbot_challenges:/var/www/certbot
    ports:
      - "80:80"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    entrypoint: >
      sh -c "sleep 5 && certbot certonly --webroot --webroot-path=/var/www/certbot 
      --email wankhedesamirforwork@gmail.com --agree-tos --no-eff-email 
      -d nthhost.credenz.co.in && echo '✅ Certbot finished successfully!'"
    depends_on:
      nginx-certbot:
        condition: service_started

  certbot-renew:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    entrypoint: >
      sh -c "certbot renew --webroot --webroot-path=/var/www/certbot && nginx -s reload"
    depends_on:
      certbot:
        condition: service_completed_successfully
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      - admin
      - backend
    restart: always
    
  backend:
    build: ./backend
    ports: 
      - "5789:3000"
    volumes:
      - data_volume:/data
    env_file:
      - .env
    depends_on:
      nginx:
        condition: service_healthy
    restart: unless-stopped

  admin:
    build: ./admin
    ports: 
      - "4788:4000"
    volumes:
      - data_volume:/data
    env_file:
      - .env
    depends_on:
      nginx:
        condition: service_healthy
    restart: unless-stopped

volumes:
  data_volume:
  letsencrypt:
  certbot_challenges:
